name: 'Easy Pull Request'
description: 'Simple and easy way to create a pull request.'
author: 'Misha Behersky'
branding:
  icon: git-pull-request
  color: white
inputs:
  github_token:
    description: 'A GitHub API token'
    required: true
  head:
    description: 'The head ref that should be pulled into base.'
    required: true
  title:
    description: 'The title of the pull request.'
    required: true
  base:
    description: 'The base branch for the pull request. Defaults to master.'
    required: false
  draft:
    description: 'Whether this should be a draft PR.'
    required: false
  body:
    description: 'The body of the pull request.'
    required: false
  assignees:
    description: 'A comma-separated list of GitHub logins that should be assigned to this PR.'
    required: false
  reviewers:
    description: 'A comma-separated list of GitHub logins that should review this PR.'
    required: false
  team_reviewers:
    description: 'A comma-separated list of GitHub team slugs that should review this PR.'
    required: false
  labels:
    description: 'A comma-separated list of labels to be set on this PR.'
    required: false
  repository:
    description: 'The repository in which the PR shall be created.'
    required: false
outputs:
  number:
    description: 'Pull Request number'
  html_url:
    description: 'URL that Pull Request may be reviewed at'
runs:
  using: 'node16'
  main: 'dist/index.js'
